import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { validateByKind } from "../../scripts/validate-contract-semantics.mjs";
import { validatePayload } from "../../scripts/validate-output.mjs";
import { sha256Canonical } from "../../packages/cineweave-runtime/src/canonical-json.mjs";
import { resolveCapabilityPlan } from "../../packages/cineweave-runtime/src/capability-resolution-runtime.mjs";
import { createExecutionPreview } from "../../packages/cineweave-runtime/src/execution-preview-runtime.mjs";

const contractRoot = resolve(process.cwd(), "packages", "cineweave-contracts");
const readExample = (name) => readFile(join(contractRoot, "examples", name), "utf8").then(JSON.parse);
const [capabilityExample, adapterExample, requestExample] = await Promise.all([
  readExample("capability-profile.json"),
  readExample("adapter-descriptor.json"),
  readExample("execution-request.json")
]);

function refFor(payload, kind, idField) {
  return { kind, id: payload[idField], version: payload.version ?? 1, contentHash: sha256Canonical(payload) };
}

function candidatePair({ suffix, support = "strong" } = {}) {
  const capability = structuredClone(capabilityExample);
  capability.profileId = `capability.runtime-${suffix}`;
  capability.adapterId = `adapter.runtime-${suffix}`;
  capability.capabilities = capability.capabilities.map((item) => item.capabilityId === "image_generation" ? { ...item, support } : item);
  capability.skillReceipt = { ...capability.skillReceipt, usedAt: "2026-09-02T06:00:00.000Z" };
  const adapter = structuredClone(adapterExample);
  adapter.adapterId = capability.adapterId;
  adapter.capabilityProfileRef = refFor(capability, capability.kind, "profileId");
  adapter.skillReceipt = { ...adapter.skillReceipt, usedAt: "2026-09-02T06:00:00.000Z" };
  return {
    candidateId: `candidate.runtime-${suffix}`,
    capabilityProfileRef: refFor(capability, capability.kind, "profileId"),
    capabilityProfile: capability,
    adapterDescriptorRef: refFor(adapter, adapter.kind, "adapterId"),
    adapterDescriptor: adapter
  };
}

function resolutionRequest(overrides = {}) {
  return {
    operationId: "image.generate.fixture",
    renderMode: "generate",
    executionMode: "fixture",
    mediaKind: "image",
    inputCount: 0,
    outputCount: 1,
    acceptedMimeTypes: ["image/svg+xml"],
    requirements: [{ requirementId: "requirement.identity", capabilityId: "image_generation", level: "hard", reason: "The image must be generated by the selected operation." }],
    ...overrides
  };
}

test("Capability Resolver ranks exact candidates deterministically and explains tradeoffs", async () => {
  const strong = candidatePair({ suffix: "strong", support: "strong" });
  const partial = candidatePair({ suffix: "partial", support: "partial" });
  const plan = resolveCapabilityPlan(resolutionRequest(), [partial, strong], { createdAt: "2026-09-02T06:10:00.000Z" });
  const replay = resolveCapabilityPlan(resolutionRequest(), [strong, partial], { createdAt: "2026-09-02T06:10:00.000Z" });
  assert.deepEqual(plan, replay);
  assert.equal(plan.status, "selected");
  assert.equal(plan.selection.selectedCandidateId, "candidate.runtime-strong");
  assert.equal(plan.candidates.find((candidate) => candidate.candidateId === "candidate.runtime-strong")?.score, 100);
  assert.equal(plan.candidates.find((candidate) => candidate.candidateId === "candidate.runtime-partial")?.status, "needs_review");
  assert.equal(plan.executionBoundary.executesAdapter, false);
  assert.equal(Object.isFrozen(plan), true);
  assert.deepEqual(validateByKind(plan, { candidates: [strong, partial] }), []);
  const schemaResult = await validatePayload(join(contractRoot, "schemas", "capability-resolution-plan.schema.json"), plan);
  assert.equal(schemaResult.valid, true);
});

test("Capability Resolver blocks an unknown hard capability instead of silently selecting a fallback", () => {
  const strong = candidatePair({ suffix: "unknown", support: "strong" });
  const plan = resolveCapabilityPlan(resolutionRequest({ requirements: [{ requirementId: "requirement.camera", capabilityId: "camera_motion", level: "hard", reason: "The camera path is a hard requirement." }] }), [strong], { createdAt: "2026-09-02T06:10:00.000Z" });
  assert.equal(plan.status, "blocked");
  assert.equal(plan.selection.selectedCandidateId, null);
  assert.equal(plan.candidates[0].hardFailures.some((failure) => failure.includes("unknown")), true);
});

test("Execution Preview exposes exact budget and leaves approval pending", async () => {
  const pair = candidatePair({ suffix: "preview", support: "strong" });
  const resolution = resolveCapabilityPlan(resolutionRequest(), [pair], { createdAt: "2026-09-02T06:10:00.000Z" });
  const resolutionRef = refFor(resolution, resolution.kind, "resolutionPlanId");
  const request = structuredClone(requestExample);
  request.requestId = "execution.runtime-preview";
  request.createdAt = "2026-09-02T06:11:00.000Z";
  request.adapterDescriptorRef = pair.adapterDescriptorRef;
  request.capabilityProfileRef = pair.capabilityProfileRef;
  request.executionMode = "fixture";
  request.authorization = { externalEffects: "denied", approvalScope: "none" };
  request.preflight = { status: "ready", exactRefsResolved: true, operationSupported: true, hardCapabilitiesSatisfied: true, rightsResolved: true, budgetResolved: true, secretsAbsent: true };
  const requestRef = refFor(request, request.kind, "requestId");
  const preview = createExecutionPreview(request, resolution, {
    executionRequestRef: requestRef,
    capabilityResolutionPlanRef: resolutionRef,
    adapterDescriptor: pair.adapterDescriptor,
    capabilityProfile: pair.capabilityProfile,
    estimatedAmount: 0,
    createdAt: "2026-09-02T06:12:00.000Z"
  });
  assert.equal(preview.status, "ready");
  assert.equal(preview.costEstimate.amount, 0);
  assert.equal(preview.approval.status, "pending");
  assert.equal(preview.approval.scope, "none");
  assert.equal(preview.executionBoundary.executesAdapter, false);
  assert.deepEqual(validateByKind(preview, { executionRequest: request, capabilityResolutionPlan: resolution }), []);
  const schemaResult = await validatePayload(join(contractRoot, "schemas", "execution-preview.schema.json"), preview);
  assert.equal(schemaResult.valid, true);

  const unknownCostPreview = createExecutionPreview(request, resolution, {
    executionRequestRef: requestRef,
    capabilityResolutionPlanRef: resolutionRef,
    adapterDescriptor: pair.adapterDescriptor,
    capabilityProfile: pair.capabilityProfile,
    createdAt: "2026-09-02T06:12:00.000Z"
  });
  assert.equal(unknownCostPreview.status, "blocked");
  assert.equal(unknownCostPreview.costEstimate.status, "unknown");
  assert.equal(unknownCostPreview.costEstimate.amount, null);
  assert.equal(unknownCostPreview.approval.status, "pending");
  assert.equal(
    unknownCostPreview.riskSummary.find((risk) => risk.riskId === "risk.cost-visibility")?.status,
    "block"
  );
  assert.equal(
    unknownCostPreview.riskSummary.find((risk) => risk.riskId === "risk.budget")?.status,
    "block"
  );
  assert.deepEqual(
    validateByKind(unknownCostPreview, { executionRequest: request, capabilityResolutionPlan: resolution }),
    []
  );
  const unknownSchemaResult = await validatePayload(
    join(contractRoot, "schemas", "execution-preview.schema.json"),
    unknownCostPreview
  );
  assert.equal(unknownSchemaResult.valid, true);
});
